class FormData {
  // Indian States and Union Territories
  static const List<String> indianStates = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
    'Other',
  ];

  // Indian Cities
  static const List<String> indianCities = [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Chennai',
    'Kolkata',
    'Pune',
    'Ahmedabad',
    'Jaipur',
    'Surat',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Pimpri-Chinchwad',
    'Patna',
    'Vadodara',
    'Ghaziabad',
    'Ludhiana',
    'Agra',
    'Nashik',
    'Faridabad',
    'Meerut',
    'Rajkot',
    'Kalyan-Dombivali',
    'Vasai-Virar',
    'Varanasi',
    'Srinagar',
    'Aurangabad',
    'Dhanbad',
    'Amritsar',
    'Allahabad',
    'Ranchi',
    'Howrah',
    'Coimbatore',
    'Jabalpur',
    'Gwalior',
    'Vijayawada',
    'Jodhpur',
    'Madurai',
    'Raipur',
    'Kota',
    'Guwahati',
    'Chandigarh',
    'Solapur',
    'Hubli-Dharwad',
    'Bareilly',
    'Moradabad',
    'Mysore',
    'Gurgaon',
    'Aligarh',
    'Jalandhar',
    'Tiruchirappalli',
    'Bhubaneswar',
    'Salem',
    'Warangal',
    'Mira-Bhayandar',
    'Thiruvananthapuram',
    'Bhiwandi',
    'Saharanpur',
    'Gorakhpur',
    'Guntur',
    'Bikaner',
    'Amravati',
    'Noida',
    'Jamshedpur',
    'Bhilai',
    'Cuttack',
    'Firozabad',
    'Kochi',
    'Nellore',
    'Bhavnagar',
    'Dehradun',
    'Durgapur',
    'Asansol',
    'Rourkela',
    'Nanded',
    'Kolhapur',
    'Ajmer',
    'Akola',
    'Gulbarga',
    'Jamnagar',
    'Ujjain',
    'Loni',
    'Siliguri',
    'Jhansi',
    'Ulhasnagar',
    'Jammu',
    'Sangli-Miraj & Kupwad',
    'Mangalore',
    'Erode',
    'Belgaum',
    'Ambattur',
    'Tirunelveli',
    'Malegaon',
    'Gaya',
    'Jalgaon',
    'Udaipur',
    'Maheshtala',
    'Tirupur',
    'Davanagere',
    'Kozhikode',
    'Akola',
    'Kurnool',
    'Rajpur Sonarpur',
    'Bokaro',
    'South Dumdum',
    'Bellary',
    'Patiala',
    'Gopalpur',
    'Agartala',
    'Bhagalpur',
    'Muzaffarnagar',
    'Bhatpara',
    'Panihati',
    'Latur',
    'Dhule',
    'Rohtak',
    'Korba',
    'Bhilwara',
    'Berhampur',
    'Muzaffarpur',
    'Ahmednagar',
    'Mathura',
    'Kollam',
    'Avadi',
    'Kadapa',
    'Kamarhati',
    'Bilaspur',
    'Shahjahanpur',
    'Satara',
    'Bijapur',
    'Rampur',
    'Shivamogga',
    'Chandrapur',
    'Junagadh',
    'Thrissur',
    'Alwar',
    'Bardhaman',
    'Kulti',
    'Kakinada',
    'Nizamabad',
    'Parbhani',
    'Tumkur',
    'Hisar',
    'Ozhukarai',
    'Bihar Sharif',
    'Panipat',
    'Darbhanga',
    'Bally',
    'Aizawl',
    'Dewas',
    'Ichalkaranji',
    'Tirupati',
    'Karnal',
    'Bathinda',
    'Rampur',
    'Shivpuri',
    'Ratlam',
    'Modinagar',
    'Delhi Cantonment',
    'Pali',
    'Ramagundam',
    'Silchar',
    'Haridwar',
    'Vijayanagaram',
    'Katihar',
    'Nagercoil',
    'Sri Ganganagar',
    'Karawal Nagar',
    'Mango',
    'Thanjavur',
    'Bulandshahr',
    'Uluberia',
    'Murwara',
    'Sambhal',
    'Singrauli',
    'Nadiad',
    'Secunderabad',
    'Naihati',
    'Yamunanagar',
    'Bidhan Nagar',
    'Pallavaram',
    'Bidar',
    'Munger',
    'Panchkula',
    'Burhanpur',
    'Raurkela Industrial Township',
    'Kharagpur',
    'Dindigul',
    'Gandhinagar',
    'Hospet',
    'Gangtok',
    'Haora',
    'Gandhidham',
    'Medinipur',
    'Achalpur',
    'Palanpur',
    'Latur',
    'Hazaribagh',
    'Kishanganj',
    'Gudivada',
    'Phagwara',
    'Durg',
    'Shimla',
    'Guntakal',
    'Sasaram',
    'Adoni',
    'Udupi',
    'Katni',
    'Proddatur',
    'Mahbubnagar',
    'Saharsa',
    'New Delhi',
    'Other',
  ];

  // Employment Status
  static const List<String> employmentStatus = [
    'Not employed',
    'Working as salaried employee',
    'Self employed',
    'Business with more than 10 employees',
  ];

  // Monthly Income Ranges
  static const List<String> monthlyIncomeRanges = [
    '10,000 - 50,000',
    '50,000 - 1,00,000',
    '1,00,000 - 3,00,000',
    '3,00,000 - 5,00,000',
    '5,00,000 or above',
  ];

  // Yes/No Options
  static const List<String> yesNoOptions = ['Yes', 'No'];

  // Credit Card Dues Ranges
  static const List<String> creditCardDuesRanges = [
    '1,00,000 - 2,00,000',
    '2,00,000 - 3,00,000',
    '3,00,000 - 4,00,000',
    '4,00,000 - 5,00,000',
    '5,00,000 - 10,00,000',
    '10,00,000 or above',
  ];

  // Personal Loan Dues Ranges
  static const List<String> personalLoanDuesRanges = [
    '1,00,000 - 2,00,000',
    '2,00,000 - 3,00,000',
    '3,00,000 - 4,00,000',
    '4,00,000 - 5,00,000',
    '5,00,000 - 10,00,000',
    '10,00,000 or above',
  ];

  static const List<String> sourceReference = [
    'Social Media',
    'Billcut',
    'Website',
    'Through a friend',
    'Other',
  ];
}
